name: Build DRA Driver image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DRIVER_IMAGE_NAME: cni-dra-driver
      DRIVER_IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      DRIVER_IMAGE_TAG: kep-5075
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DRIVER_IMAGE_REGISTRY }}/${{ env.DRIVER_IMAGE_NAME }}:${{ env.DRIVER_IMAGE_TAG }}
          file: ./build/cni-dra-driver/Dockerfile
